# Generated by Django 6.0.2 on 2026-02-18 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='gateway_response',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='refund_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='refund_reason',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='refunded_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verification_timestamp',
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('cod', 'Cash on Delivery')], default='card', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verified_by_backend',
            field=models.BooleanField(default=False),
        ),
    ]
