# Generated by Django 5.0.1 on 2026-02-14 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, help_text='Written review')),
                ('review_images', models.JSONField(blank=True, default=list, help_text='Images of the completed dress')),
                ('designer_response', models.TextField(blank=True, help_text="Designer's response to the review")),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the review is verified by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
