# Generated by Django 5.0.1 on 2026-02-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DressRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_type', models.CharField(choices=[('wedding', 'Wedding Dress'), ('evening', 'Evening Gown'), ('casual', 'Casual Dress'), ('formal', 'Formal Dress'), ('traditional', 'Traditional Dress'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the desired dress')),
                ('reference_images', models.JSONField(blank=True, default=list, help_text='List of reference/inspiration image URLs')),
                ('bust', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('additional_measurements', models.JSONField(blank=True, default=dict, help_text='Additional measurements as key-value pairs')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text="Customer's budget for the dress", max_digits=10, null=True)),
                ('deadline', models.DateField(blank=True, help_text='Desired completion date', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('designer_notes', models.TextField(blank=True, help_text="Designer's notes or response to the request")),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price quoted by designer', max_digits=10, null=True)),
                ('estimated_completion', models.DateField(blank=True, help_text="Designer's estimated completion date", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
