# Generated by Django 6.0.2 on 2026-02-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress_requests', '0003_add_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dressrequest',
            name='preferred_color',
            field=models.CharField(default='#ffffff', help_text='Hex color code', max_length=7),
        ),
    ]
