# Generated by Django 5.1.5 on 2026-02-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress_requests', '0004_alter_dressrequest_preferred_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='dressrequest',
            name='hemline',
            field=models.CharField(blank=True, choices=[('mini', 'Mini'), ('knee', 'Knee-length'), ('midi', 'Midi'), ('maxi', 'Maxi'), ('floor', 'Floor-length'), ('asymmetrical', 'Asymmetrical'), ('high-low', 'High-Low')], max_length=20),
        ),
        migrations.AddField(
            model_name='dressrequest',
            name='neck_type',
            field=models.CharField(blank=True, choices=[('v-neck', 'V-Neck'), ('round', 'Round Neck'), ('square', 'Square Neck'), ('halter', 'Halter'), ('off-shoulder', 'Off-Shoulder'), ('boat', 'Boat Neck'), ('high', 'High Neck'), ('scoop', 'Scoop Neck')], max_length=20),
        ),
        migrations.AddField(
            model_name='dressrequest',
            name='reference_photo',
            field=models.ImageField(blank=True, help_text='Upload a reference photo', null=True, upload_to='requests/photos/'),
        ),
    ]
