# Generated by Django 6.0.2 on 2026-02-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alterationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('paid', 'Paid'), ('in_progress', 'Tailoring'), ('ready', 'Ready'), ('shipped', 'Shipping'), ('delivered', 'Delivered'), ('altering', 'Altering'), ('completed', 'Done'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
