# Generated by Django 5.0.1 on 2026-02-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('specialties', models.CharField(choices=[('wedding', 'Wedding Dresses'), ('casual', 'Casual Wear'), ('evening', 'Evening Wear'), ('formal', 'Formal Wear'), ('traditional', 'Traditional Wear'), ('custom', 'Custom Designs')], default='custom', max_length=50)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('price_range_min', models.DecimalField(decimal_places=2, help_text='Minimum price in currency', max_digits=10)),
                ('price_range_max', models.DecimalField(decimal_places=2, help_text='Maximum price in currency', max_digits=10)),
                ('portfolio_images', models.JSONField(blank=True, default=list, help_text='List of portfolio image URLs')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from reviews', max_digits=3)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_available', models.BooleanField(default=True, help_text='Whether designer is accepting new requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', '-total_orders'],
            },
        ),
    ]
