# Generated by Django 6.0.2 on 2026-02-15 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='designs/')),
                ('category', models.CharField(choices=[('wedding', 'Wedding Dresses'), ('casual', 'Casual Wear'), ('evening', 'Evening Wear'), ('formal', 'Formal Wear'), ('traditional', 'Traditional Wear'), ('custom', 'Custom Designs')], default='custom', max_length=50)),
                ('price_estimate', models.DecimalField(blank=True, decimal_places=2, help_text='Starting price for this design', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='designers.designerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
